/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TranslateView.java
 *
 * Created on Feb 1, 2010, 3:21:49 PM
 */

package com.ben.IA.Views.utilities;

import com.ben.IA.App.IAApp;
import com.google.api.translate.Language;
import com.google.api.translate.Translate;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author benoitdaccache
 */
public class TranslateView extends javax.swing.JFrame {

    /** Creates new form TranslateView */
    public TranslateView() {
        initComponents();
        this.setLocationRelativeTo(IAApp.getApplication().getMainFrame());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromCombo = new javax.swing.JComboBox();
        toCombo = new javax.swing.JComboBox();
        goButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        toTranslateText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        translatedText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        fromCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fr", "En", "De", "Es", "Nl", "Ar" }));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.IA.App.IAApp.class).getContext().getResourceMap(TranslateView.class);
        fromCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("fromCombo.border.title"))); // NOI18N
        fromCombo.setName("fromCombo"); // NOI18N

        toCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En", "Fr", "De", "Es", "Nl", "Ar" }));
        toCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("toCombo.border.title"))); // NOI18N
        toCombo.setName("toCombo"); // NOI18N

        goButton.setText(resourceMap.getString("goButton.text")); // NOI18N
        goButton.setName("goButton"); // NOI18N
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        toTranslateText.setColumns(20);
        toTranslateText.setLineWrap(true);
        toTranslateText.setRows(5);
        toTranslateText.setName("toTranslateText"); // NOI18N
        jScrollPane1.setViewportView(toTranslateText);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        translatedText.setColumns(20);
        translatedText.setEditable(false);
        translatedText.setLineWrap(true);
        translatedText.setRows(5);
        translatedText.setName("translatedText"); // NOI18N
        jScrollPane2.setViewportView(translatedText);

        jSplitPane1.setBottomComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(toCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(goButton))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        try {
            Translate.setHttpReferrer("www.google.com");
            Language from = Language.validate((String) fromCombo.getSelectedItem());
            Language to = Language.validate((String) toCombo.getSelectedItem());
            to.toString();
            String translated = Translate.execute(toTranslateText.getText(), from, to);
            translatedText.setText(translated);
        } catch (Exception ex) {
            Logger.getLogger(TranslateView.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_goButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fromCombo;
    private javax.swing.JButton goButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox toCombo;
    private javax.swing.JTextArea toTranslateText;
    private javax.swing.JTextArea translatedText;
    // End of variables declaration//GEN-END:variables

}
