/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotesViewer.java
 *
 * Created on Feb 1, 2010, 1:37:00 PM
 */
package com.ben.IA.Views.notes;

import com.ben.IA.App.IAApp;
import com.ben.IA.brain.database.Notes;
import java.awt.print.PrinterException;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author benoitdaccache
 */
public class NotesViewer extends javax.swing.JFrame {

    private Hashtable<String, String> notes;
    private DefaultListModel listModel;
    private String noteTitle;

    /** Creates new form NotesViewer */
    public NotesViewer(Hashtable<String, String> notes) {
        initComponents();
        this.setLocationRelativeTo(IAApp.getApplication().getMainFrame());
        this.notes = notes;
        fillList();
    }

    private void fillList() {
        listModel = new DefaultListModel();
        Enumeration<String> e = notes.keys();
        while (e.hasMoreElements())
            listModel.addElement(e.nextElement());
        notesList.setModel(listModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesList = new javax.swing.JList();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        notesField.setColumns(20);
        notesField.setEditable(false);
        notesField.setRows(5);
        notesField.setName("notesField"); // NOI18N
        jScrollPane2.setViewportView(notesField);

        jSplitPane1.setRightComponent(jScrollPane2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.IA.App.IAApp.class).getContext().getResourceMap(NotesViewer.class);
        notesList.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("notesList.border.title"))); // NOI18N
        notesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        notesList.setName("notesList"); // NOI18N
        notesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(notesList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        editButton.setText(resourceMap.getString("editButton.text")); // NOI18N
        editButton.setEnabled(false);
        editButton.setName("editButton"); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setEnabled(false);
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText(resourceMap.getString("deleteButton.text")); // NOI18N
        deleteButton.setEnabled(false);
        deleteButton.setName("deleteButton"); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        printButton.setText(resourceMap.getString("printButton.text")); // NOI18N
        printButton.setName("printButton"); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(printButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesListMouseClicked
        if (listModel.getSize() != 0)
            printNoteToScreen(notesList.getSelectedIndex());
    }//GEN-LAST:event_notesListMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        notesField.setEditable(true);
        editButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Notes.getInstance().editNote(noteTitle, notesField.getText());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Notes.getInstance().removeNote(noteTitle);
        listModel.removeElement(noteTitle);
        notesList.setModel(listModel);
        deleteButton.setEnabled(false);
        notesField.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed
    private void printNoteToScreen(int selectedIndex) {
        String val = (String) listModel.getElementAt(selectedIndex);
        String note = notes.get(val);
        noteTitle = val;
        notesField.setText(note);
        editButton.setEnabled(true);
        saveButton.setEnabled(false);
        deleteButton.setEnabled(true);
    }
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            notesField.print();
        } catch (PrinterException ex) {
            Logger.getLogger(NotesViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_printButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea notesField;
    private javax.swing.JList notesList;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
