/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemUsageView.java
 *
 * Created on Feb 5, 2010, 5:13:20 PM
 */
package com.ben.IA.brain.scripter;

import com.ben.IA.brain.scripter.grapher.GraphPanel;
import java.text.NumberFormat;

/**
 *
 * @author benoitdaccache
 */
public class MemUsageView extends javax.swing.JFrame {

    private GraphPanel graphPanel;
    int i = 0;

    /** Creates new form MemUsageView */
    public MemUsageView() {
        initComponents();
        graphPanel = new GraphPanel();
        graphPanel.setSize(254, 254);
        graphPanel.setLocation(200, 0);
        this.add(graphPanel);
        Runnable r = new Runnable() {

            public void run() {
                while (true)
                    try {
                        checkMem();
                        i++;
                        if (i > 254)
                            i = 0;
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                    }
            }
        };
        new Thread(r).start();
    }

    private void checkMem() {
        Runtime runtime = Runtime.getRuntime();

        NumberFormat format = NumberFormat.getInstance();

        StringBuilder sb = new StringBuilder();
        long maxMemory = runtime.maxMemory();
        long allocatedMemory = runtime.totalMemory();
        long freeMemory = runtime.freeMemory();
        memoryTable.setValueAt("free memory", 0, 0);
        memoryTable.setValueAt("allocated memory", 1, 0);
        memoryTable.setValueAt("max memory", 2, 0);
        memoryTable.setValueAt("total free memory", 3, 0);

        memoryTable.setValueAt(format.format(freeMemory / 1024), 0, 1);
        memoryTable.setValueAt(format.format(allocatedMemory / 1024), 1, 1);
        memoryTable.setValueAt(format.format(maxMemory / 1024), 2, 1);
        memoryTable.setValueAt(format.format((freeMemory + (maxMemory - allocatedMemory)) / 1024), 3, 1);
        long ing = (freeMemory * 200 / allocatedMemory);
        int fin = 254 - (int) (freeMemory * 254 / allocatedMemory);
        try {
            graphPanel.drawPoint(i, fin);
        } catch (NullPointerException e) {
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.IA.App.IAApp.class).getContext().getResourceMap(MemUsageView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setLocationByPlatform(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(254, 254));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        memoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "MB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        memoryTable.setName("memoryTable"); // NOI18N
        memoryTable.setPreferredSize(new java.awt.Dimension(200, 64));
        jScrollPane1.setViewportView(memoryTable);
        memoryTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("memoryTable.columnModel.title0")); // NOI18N
        memoryTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("memoryTable.columnModel.title1")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memoryTable;
    // End of variables declaration//GEN-END:variables
}
